run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - unconvert
    - gocritic

linters-settings:
  govet:
    enable-all: true
    disable:
      - fieldalignment
      - shadow
  gocritic:
    disabled-checks:
      - dupImport
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
